# Generated by Django 5.0.6 on 2024-07-07 18:01

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutricion', '0002_receta_body_alter_receta_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='body',
        ),
        migrations.AlterField(
            model_name='receta',
            name='detalle',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
